version: "3.2"
services:
  dev:
    image: tianon/true
    restart: "no"
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres:13
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - "dbdata:/var/lib/postgresql/data"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - esnet
    volumes:
      - "esdata:/usr/share/elasticsearch/data"

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:7.10.1
    ports:
      - "5601:5601"
    networks:
      - esnet
    depends_on:
      - elasticsearch
    environment:
      - SERVER_NAME=127.0.0.1
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  dbdata:
  esdata:

networks:
  esnet:
